"""empty message

Revision ID: d4c56967e08e
Revises: f202b6f49685
Create Date: 2026-04-03 00:54:35.209183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4c56967e08e'
down_revision = 'f202b6f49685'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_key', sa.String(length=120), nullable=True))
        batch_op.create_unique_constraint('uq_user_api_key', ['api_key'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_api_key', type_='unique')
        batch_op.drop_column('api_key')

    # ### end Alembic commands ###
